version: "3.9"
services:
  postgres:
    container_name: postgres_shaik
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data 
    ports:
      - "${POSTGRES_PORT}:5432"