// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	pb "go-labiblioteca-backend/pb"
)

// BookRepoClient is an autogenerated mock type for the BookRepoClient type
type BookRepoClient struct {
	mock.Mock
}

// CreateBook provides a mock function with given fields: ctx, in, opts
func (_m *BookRepoClient) CreateBook(ctx context.Context, in *pb.CreateBookRequest, opts ...grpc.CallOption) (*pb.CreateBookResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *pb.CreateBookResponse
	if rf, ok := ret.Get(0).(func(context.Context, *pb.CreateBookRequest, ...grpc.CallOption) *pb.CreateBookResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.CreateBookResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.CreateBookRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookByID provides a mock function with given fields: ctx, in, opts
func (_m *BookRepoClient) GetBookByID(ctx context.Context, in *pb.GetBookByIDRequest, opts ...grpc.CallOption) (*pb.GetBookByIDResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *pb.GetBookByIDResponse
	if rf, ok := ret.Get(0).(func(context.Context, *pb.GetBookByIDRequest, ...grpc.CallOption) *pb.GetBookByIDResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.GetBookByIDResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.GetBookByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBookRepoClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewBookRepoClient creates a new instance of BookRepoClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBookRepoClient(t mockConstructorTestingTNewBookRepoClient) *BookRepoClient {
	mock := &BookRepoClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
