// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeBookRepoServer is an autogenerated mock type for the UnsafeBookRepoServer type
type UnsafeBookRepoServer struct {
	mock.Mock
}

// mustEmbedUnimplementedBookRepoServer provides a mock function with given fields:
func (_m *UnsafeBookRepoServer) mustEmbedUnimplementedBookRepoServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeBookRepoServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeBookRepoServer creates a new instance of UnsafeBookRepoServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeBookRepoServer(t mockConstructorTestingTNewUnsafeBookRepoServer) *UnsafeBookRepoServer {
	mock := &UnsafeBookRepoServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
