// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlcgen

type Book struct {
	ID          int64
	Isbn        string
	Title       string
	Description string
	Author      string
	ImageUrl    string
}
